name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2
       
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push the backend
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: gerrome/php-react-stack_backend:1.2
       

      - name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          context: ./react
          push: true
          tags: gerrome/php-react-stack_client:1.2

      - name: Build and push nginx
        uses: docker/build-push-action@v3
        with:
          context: ./nginx
          push: true
          tags: gerrome/php-react-stack_nginx:1
